// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLyZb3PZWrjEzSd5kj6BaRkOPcg_cvJR4',
    appId: '1:199573533447:web:70fa4e6d47b2db75730ba2',
    messagingSenderId: '199573533447',
    projectId: 'no-due-form',
    authDomain: 'no-due-form.firebaseapp.com',
    storageBucket: 'no-due-form.appspot.com',
    measurementId: 'G-072QTZNR60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdiHwbDmLmQNxtF2QTVWfnldYSWvfTTQ',
    appId: '1:199573533447:android:b40f655858efb8b4730ba2',
    messagingSenderId: '199573533447',
    projectId: 'no-due-form',
    storageBucket: 'no-due-form.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1j_qwmoo78-4eV5_4AmTwavR80HdR7wY',
    appId: '1:199573533447:ios:18b6373c8a7c6c10730ba2',
    messagingSenderId: '199573533447',
    projectId: 'no-due-form',
    storageBucket: 'no-due-form.appspot.com',
    iosBundleId: 'com.example.noDueForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1j_qwmoo78-4eV5_4AmTwavR80HdR7wY',
    appId: '1:199573533447:ios:18b6373c8a7c6c10730ba2',
    messagingSenderId: '199573533447',
    projectId: 'no-due-form',
    storageBucket: 'no-due-form.appspot.com',
    iosBundleId: 'com.example.noDueForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLyZb3PZWrjEzSd5kj6BaRkOPcg_cvJR4',
    appId: '1:199573533447:web:c0845c203f6179db730ba2',
    messagingSenderId: '199573533447',
    projectId: 'no-due-form',
    authDomain: 'no-due-form.firebaseapp.com',
    storageBucket: 'no-due-form.appspot.com',
    measurementId: 'G-BFRZB7DH39',
  );
}
